name: FastAPI Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: 3.11.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Directory Structure
      run: |
        ls -la
        echo "Current directory contents:"
        find . -type d

    - name: Build Static Site
      run: |
        mkdir -p dist
        if [ -d "GUI/templates" ]; then
          echo "Copying from GUI/templates"
          cp -r GUI/templates dist/
        elif [ -d ".venv/GUI/templates" ]; then
          echo "Copying from .venv/GUI/templates"
          cp -r .venv/GUI/templates dist/
        else
          echo "Templates directory not found"
          exit 1
        fi

        if [ -d "GUI/static" ]; then
          echo "Copying from GUI/static"
          cp -r GUI/static dist/
        elif [ -d ".venv/GUI/static" ]; then
          echo "Copying from .venv/GUI/static"
          cp -r .venv/GUI/static dist/
        else
          echo "Static directory not found"
          exit 1
        fi

        if [ -f "dist/templates/chat.html" ]; then
          cp dist/templates/chat.html dist/index.html
        else
          echo "chat.html not found"
          exit 1
        fi
        
        touch dist/.nojekyll

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: fastapi-build
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: fastapi-build
